# Generated by Django 5.1 on 2024-10-06 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_task_type_alter_task_datecompleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='important',
        ),
    ]
