# Generated by Django 5.1 on 2024-10-06 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_remove_task_important'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('university', 'Universitaria'), ('personal', 'Personal'), ('work', 'Laboral')], default='normal', max_length=10),
        ),
    ]
