# Generated by Django 5.1 on 2024-10-09 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('university', 'Universitaria'), ('personal', 'Personal'), ('work', 'Laboral')], default='personal', max_length=10),
        ),
    ]
